### PR TITLE
Update collection for certification

### PR DESCRIPTION
**Pull request by thedoubl3j**
Apologies on the delay for this. 

**Meta Directory**

Used to house mainly the runtime.yml file which can house a bunch of things like redirects etc if you all need to rename/deprecate modules etc. This change explicitly states what version of ansible-core the collection supports. given 2.9 is EOL and will be EOL downstream soon, I dropped 2.13 in but I can change this to whatever supported version you all wish to start with and want to test against. This is displayed to users via the collection page so it can be used a support statement. 

**Python file changes** 

I ran the sanity suite over the collection from the latest core release, 2.15.2, and saw some errors. I started addressing some of them but then released as I got to the unused imports, it was probably best for you all to do that given that I only CI lint outputs and I don't necessarily know the code base well and what it is interacting with at all. 

httpapi and the test fix were all pep8 violations and then you can start to see the unused import removals where I stopped. 

The primary offender was just unused imports from pylint around `re` not being used. Happy to fix those here or let you all deal with them.

**Running Sanity** 

Can be done in CLI or easily from your dev environment, the collection will need to be built and installed, then just run `ansible-test sanity` at the top level of the collection install location (default is ~/.ansible/collections/ansible_collections/opengear/om). Optionally, if docker is installed, you can pass the --docker argument and ansible-test will pull down and run the sanity suite against all supported core python versions (you don't have to support them, they can be ignored and suppressed with a file).

### CODE REVIEW

**Comment by alisonlhart** [comment]
I also see that the collection is missing a changelog file. It can be any of the following: CHANGELOG.rst, CHANGELOG.md, changelogs/changelog.yml file. The `antsibull` tool can easily generate CHANGELOG.rst files: https://github.com/ansible-community/antsibull

**Comment by mattwit** [comment]
Thanks! No worries, you can go ahead and make the changes.

**Comment by mattwit** [comment]
@thedoubl3j we're ok with you generating a changelog.  Sorry for the delayed response!!!

**Comment by alisonlhart** [comment]
@mattwit I was unable to generate a changelog with the antsibull-changelog tool, because it errored out on the lack of documentation block in the `httpapi/om.py` plugin. 
For next steps, see the documentation on creating module documentation blocks [here](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html), specifics on plugin options [here](https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#plugin-configuration-documentation-standards), and an example of an httpapi documentation block can be seen [here](https://github.com/F5Networks/f5-ansible-f5os/blob/devel/ansible_collections/f5networks/f5os/plugins/httpapi/f5os.py). 

After this fix is in place, you should be able to easily generate a changelog after installing and running the antsibull-changelog tool. 

Please let us know if you have any questions as you move forward! This PR is ready to merge.

**Comment by alisonlhart** [comment]
@mattwit I see you added the comment header with the license info, which is a good start! It looks like the primary documentation blocks are still missing with the plugin info. The blocks I'm referring to can be seen in other opengear modules. For example: https://github.com/opengear/opengear.om/blob/master/plugins/modules/om_conns.py#L32-L185

The documentation and links from the previous comment provide additional details on how to build these module/plugin documentation blocks.

**Comment by mattwit** [comment]
@alisonlhart Think we got it now. Let me know!

**Comment by alisonlhart** [comment]
@mattwit That plugin seems to be passing now, but I found some other errors with building the documentation in other plugins. I recommend running ansible-doc and antsibull-changelog on the collection in your dev environment to troubleshoot and make sure all the documentation is set up correctly. Then you'll be able to generate the changelog as needed. 
https://docs.ansible.com/ansible/latest/cli/ansible-doc.html
https://github.com/ansible-community/antsibull-changelog/tree/main

I also saw there are hashed passwords in some of the unit tests, which you may want to exclude from the collection build using the "build_ignore" list in the galaxy.yml file.

**Comment by mattwit** [comment]
@alisonlhart Thanks for the help! The documentation blocks have been updated and look to be passing ansible-doc now. I've also added build_ignore to the galaxy.yml as suggested.

**Comment by alisonlhart** [comment]
@mattwit Awesome! Feel free to merge this PR then. 

After these changes, only the following are needed for certification:
- Passing ansible-test sanity: https://docs.ansible.com/ansible/latest/dev_guide/testing_sanity.html
- Passing ansible-lint: https://ansible.readthedocs.io/projects/lint/
- Adding changelog with the resources above

**Comment by Everyone2022** [comment]
@mattwit, thanks for running sanity & lint and adding a changelog to the resources. @alisonlhart, could you let us know if there are any other requirements for certification? Thanks!

**Comment by Everyone2022** [comment]
@mattwit  thanks for running sanity & lint and adding changelog to the resources. @alisonlhart  could you let us know if there are any other requirements for the certification? Thanks!

**Pull request merged**
